/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NLW Connect
 * OpenAPI spec version: 0.1
 */
import type { GetRanking200RankingItem } from './getRanking200RankingItem';

export type GetRanking200 = {
  ranking: GetRanking200RankingItem[];
};
