/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NLW Connect
 * OpenAPI spec version: 0.1
 */

export type SubscribeToEventBody = {
  name: string;
  email: string;
  /** @nullable */
  referrer?: string | null;
};
