import "./globals.css";

import { Montserrat, Oxanium } from "next/font/google";

import type { Metadata } from "next";

const oxanium = Oxanium({
	subsets: ["latin"],
	weight: ["500", "600"],
	variable: "--font-oxanium",
});

const montserrat = Montserrat({
	weight: ["400", "600"],
	subsets: ["latin"],
	variable: "--font-montserrat",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR" className={`${oxanium.variable} ${montserrat.variable}`}>
			<body className="bg-[url(/background.png)] bg-gray-900 bg-no-repeat bg-top md:bg-right-top text-gray-100 antialiased">
				<main className="mx-auto px-5 py-8 md:py-0 max-w-[1280px]">
					{children}
				</main>
			</body>
		</html>
	);
}
